name: "Automatic Connection Keeper invoker"
on:
  schedule: 
    - cron: '45 17 * * *'
  workflow_dispatch:
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        # full log
        fetch-depth: 0
    - name: Generate token
      id: generate_token
      uses: getsentry/action-github-app-token@v3
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
    - run: |
        date > "$GITHUB_WORKSPACE/ACK.txt"
        git config user.name "${{ secrets.APP_LOGIN }}[bot]"
        git config user.email "${{ secrets.APP_USER_ID }}+${{ secrets.APP_LOGIN}}[bot]@users.noreply.github.com"
        git commit -a -m "update"
        git push 'https://${{ secrets.APP_LOGIN }}:${{ steps.generate_token.outputs.token }}@github.com/ksrgtech/ACK.git'
